// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UsedCars.DAL;

#nullable disable

namespace UsedCars.DAL.Migrations
{
    [DbContext(typeof(UsedCarsContext))]
    [Migration("20220404195406_DataSeeding")]
    partial class DataSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("UsedCars.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Licensed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(2018, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Volkswagen",
                            Model = "Jetta III",
                            Price = 12947.52m,
                            WarehouseId = 1,
                            Year = 1995
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(2018, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Chevrolet",
                            Model = "Corvette",
                            Price = 20019.64m,
                            WarehouseId = 1,
                            Year = 2004
                        },
                        new
                        {
                            Id = 3,
                            DateAdded = new DateTime(2018, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Ford",
                            Model = "Expedition EL",
                            Price = 27323.42m,
                            WarehouseId = 1,
                            Year = 2008
                        },
                        new
                        {
                            Id = 4,
                            DateAdded = new DateTime(2018, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Infiniti",
                            Model = "FX",
                            Price = 8541.62m,
                            WarehouseId = 1,
                            Year = 2010
                        },
                        new
                        {
                            Id = 5,
                            DateAdded = new DateTime(2018, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "GMC",
                            Model = "Safari",
                            Price = 14772.5m,
                            WarehouseId = 1,
                            Year = 1998
                        },
                        new
                        {
                            Id = 6,
                            DateAdded = new DateTime(2018, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Plymouth",
                            Model = "Colt Vista",
                            Price = 6642.45m,
                            WarehouseId = 1,
                            Year = 1994
                        },
                        new
                        {
                            Id = 7,
                            DateAdded = new DateTime(2018, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Cadillac",
                            Model = "Escalade ESV",
                            Price = 24925.75m,
                            WarehouseId = 1,
                            Year = 2008
                        },
                        new
                        {
                            Id = 8,
                            DateAdded = new DateTime(2018, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Mitsubishi",
                            Model = "Pajero",
                            Price = 28619.45m,
                            WarehouseId = 1,
                            Year = 2002
                        },
                        new
                        {
                            Id = 9,
                            DateAdded = new DateTime(2017, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Infiniti",
                            Model = "Q",
                            Price = 6103.4m,
                            WarehouseId = 1,
                            Year = 1995
                        },
                        new
                        {
                            Id = 10,
                            DateAdded = new DateTime(2018, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Ford",
                            Model = "Mustang",
                            Price = 18992.7m,
                            WarehouseId = 1,
                            Year = 1993
                        },
                        new
                        {
                            Id = 11,
                            DateAdded = new DateTime(2018, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Chevrolet",
                            Model = "G-Series 1500",
                            Price = 23362.41m,
                            WarehouseId = 1,
                            Year = 1997
                        },
                        new
                        {
                            Id = 12,
                            DateAdded = new DateTime(2018, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Cadillac",
                            Model = "DeVille",
                            Price = 18371.53m,
                            WarehouseId = 1,
                            Year = 1993
                        },
                        new
                        {
                            Id = 13,
                            DateAdded = new DateTime(2018, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Acura",
                            Model = "NSX",
                            Price = 23175.76m,
                            WarehouseId = 1,
                            Year = 2001
                        },
                        new
                        {
                            Id = 14,
                            DateAdded = new DateTime(2018, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Ford",
                            Model = "Econoline E250",
                            Price = 26605.54m,
                            WarehouseId = 1,
                            Year = 1994
                        },
                        new
                        {
                            Id = 15,
                            DateAdded = new DateTime(2017, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Lexus",
                            Model = "GX",
                            Price = 27395.26m,
                            WarehouseId = 1,
                            Year = 2005
                        },
                        new
                        {
                            Id = 16,
                            DateAdded = new DateTime(2018, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Dodge",
                            Model = "Ram Van 3500",
                            Price = 6244.51m,
                            WarehouseId = 1,
                            Year = 1999
                        },
                        new
                        {
                            Id = 17,
                            DateAdded = new DateTime(2017, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Dodge",
                            Model = "Caravan",
                            Price = 16145.27m,
                            WarehouseId = 1,
                            Year = 1995
                        },
                        new
                        {
                            Id = 18,
                            DateAdded = new DateTime(2018, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Dodge",
                            Model = "Dynasty",
                            Price = 15103.84m,
                            WarehouseId = 1,
                            Year = 1992
                        },
                        new
                        {
                            Id = 19,
                            DateAdded = new DateTime(2018, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Dodge",
                            Model = "Ram 1500",
                            Price = 9977.65m,
                            WarehouseId = 1,
                            Year = 2004
                        },
                        new
                        {
                            Id = 20,
                            DateAdded = new DateTime(2017, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Maserati",
                            Model = "Coupe",
                            Price = 19957.71m,
                            WarehouseId = 2,
                            Year = 2005
                        },
                        new
                        {
                            Id = 21,
                            DateAdded = new DateTime(2017, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Isuzu",
                            Model = "Rodeo",
                            Price = 6303.99m,
                            WarehouseId = 2,
                            Year = 1998
                        },
                        new
                        {
                            Id = 22,
                            DateAdded = new DateTime(2017, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Infiniti",
                            Model = "I",
                            Price = 6910.16m,
                            WarehouseId = 2,
                            Year = 2002
                        },
                        new
                        {
                            Id = 23,
                            DateAdded = new DateTime(2018, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Nissan",
                            Model = "Altima",
                            Price = 8252.66m,
                            WarehouseId = 2,
                            Year = 1994
                        },
                        new
                        {
                            Id = 24,
                            DateAdded = new DateTime(2018, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Toyota",
                            Model = "Corolla",
                            Price = 23732.11m,
                            WarehouseId = 2,
                            Year = 2009
                        },
                        new
                        {
                            Id = 25,
                            DateAdded = new DateTime(2018, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Acura",
                            Model = "MDX",
                            Price = 8487.19m,
                            WarehouseId = 2,
                            Year = 2011
                        },
                        new
                        {
                            Id = 26,
                            DateAdded = new DateTime(2017, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "BMW",
                            Model = "7 Series",
                            Price = 29069.52m,
                            WarehouseId = 2,
                            Year = 1998
                        },
                        new
                        {
                            Id = 27,
                            DateAdded = new DateTime(2018, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Nissan",
                            Model = "Maxima",
                            Price = 11187.68m,
                            WarehouseId = 2,
                            Year = 2004
                        },
                        new
                        {
                            Id = 28,
                            DateAdded = new DateTime(2017, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Audi",
                            Model = "A8",
                            Price = 16047.9m,
                            WarehouseId = 2,
                            Year = 1999
                        },
                        new
                        {
                            Id = 29,
                            DateAdded = new DateTime(2018, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Nissan",
                            Model = "Murano",
                            Price = 25859.78m,
                            WarehouseId = 2,
                            Year = 2005
                        },
                        new
                        {
                            Id = 30,
                            DateAdded = new DateTime(2017, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Acura",
                            Model = "RL",
                            Price = 13232.13m,
                            WarehouseId = 2,
                            Year = 2010
                        },
                        new
                        {
                            Id = 31,
                            DateAdded = new DateTime(2018, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Mitsubishi",
                            Model = "Chariot",
                            Price = 15665.23m,
                            WarehouseId = 2,
                            Year = 1987
                        },
                        new
                        {
                            Id = 32,
                            DateAdded = new DateTime(2018, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "GMC",
                            Model = "3500 Club Coupe",
                            Price = 18129.37m,
                            WarehouseId = 2,
                            Year = 1992
                        },
                        new
                        {
                            Id = 33,
                            DateAdded = new DateTime(2017, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Dodge",
                            Model = "Dakota",
                            Price = 14479.37m,
                            WarehouseId = 2,
                            Year = 2009
                        },
                        new
                        {
                            Id = 34,
                            DateAdded = new DateTime(2018, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Mercury",
                            Model = "Grand Marquis",
                            Price = 20614.72m,
                            WarehouseId = 2,
                            Year = 1996
                        },
                        new
                        {
                            Id = 35,
                            DateAdded = new DateTime(2018, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Kia",
                            Model = "Sportage",
                            Price = 27106.47m,
                            WarehouseId = 2,
                            Year = 2001
                        },
                        new
                        {
                            Id = 36,
                            DateAdded = new DateTime(2017, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Chevrolet",
                            Model = "Blazer",
                            Price = 14835.48m,
                            WarehouseId = 2,
                            Year = 1994
                        },
                        new
                        {
                            Id = 37,
                            DateAdded = new DateTime(2018, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Mercedes-Benz",
                            Model = "SL-Class",
                            Price = 27717.28m,
                            WarehouseId = 2,
                            Year = 1994
                        },
                        new
                        {
                            Id = 38,
                            DateAdded = new DateTime(2018, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Honda",
                            Model = "Civic Si",
                            Price = 18569.86m,
                            WarehouseId = 2,
                            Year = 2003
                        },
                        new
                        {
                            Id = 39,
                            DateAdded = new DateTime(2018, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Mercedes-Benz",
                            Model = "CL-Class",
                            Price = 23494.78m,
                            WarehouseId = 2,
                            Year = 2002
                        },
                        new
                        {
                            Id = 40,
                            DateAdded = new DateTime(2018, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Volkswagen",
                            Model = "Jetta",
                            Price = 25469.49m,
                            WarehouseId = 2,
                            Year = 2006
                        },
                        new
                        {
                            Id = 41,
                            DateAdded = new DateTime(2018, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Pontiac",
                            Model = "Grand Prix",
                            Price = 11600.74m,
                            WarehouseId = 2,
                            Year = 1975
                        },
                        new
                        {
                            Id = 42,
                            DateAdded = new DateTime(2018, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Infiniti",
                            Model = "FX",
                            Price = 22000.62m,
                            WarehouseId = 2,
                            Year = 2012
                        },
                        new
                        {
                            Id = 43,
                            DateAdded = new DateTime(2018, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Jaguar",
                            Model = "XK",
                            Price = 10260.79m,
                            WarehouseId = 2,
                            Year = 2006
                        },
                        new
                        {
                            Id = 44,
                            DateAdded = new DateTime(2018, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Cadillac",
                            Model = "STS",
                            Price = 13740.2m,
                            WarehouseId = 2,
                            Year = 2007
                        },
                        new
                        {
                            Id = 45,
                            DateAdded = new DateTime(2017, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Pontiac",
                            Model = "Sunfire",
                            Price = 28489.1m,
                            WarehouseId = 2,
                            Year = 1997
                        },
                        new
                        {
                            Id = 46,
                            DateAdded = new DateTime(2018, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Cadillac",
                            Model = "SRX",
                            Price = 26750.38m,
                            WarehouseId = 2,
                            Year = 2004
                        },
                        new
                        {
                            Id = 47,
                            DateAdded = new DateTime(2018, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Land Rover",
                            Model = "Freelander",
                            Price = 21770.59m,
                            WarehouseId = 2,
                            Year = 2004
                        },
                        new
                        {
                            Id = 48,
                            DateAdded = new DateTime(2018, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Suzuki",
                            Model = "Forenza",
                            Price = 28834.26m,
                            WarehouseId = 2,
                            Year = 2005
                        },
                        new
                        {
                            Id = 49,
                            DateAdded = new DateTime(2018, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Saab",
                            Model = "9-7X",
                            Price = 25975.68m,
                            WarehouseId = 2,
                            Year = 2005
                        },
                        new
                        {
                            Id = 50,
                            DateAdded = new DateTime(2018, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Ford",
                            Model = "Fusion",
                            Price = 28091.96m,
                            WarehouseId = 2,
                            Year = 2012
                        },
                        new
                        {
                            Id = 51,
                            DateAdded = new DateTime(2018, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Cadillac",
                            Model = "Escalade",
                            Price = 7429.18m,
                            WarehouseId = 3,
                            Year = 2005
                        },
                        new
                        {
                            Id = 52,
                            DateAdded = new DateTime(2017, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Porsche",
                            Model = "Cayenne",
                            Price = 17066.31m,
                            WarehouseId = 3,
                            Year = 2011
                        },
                        new
                        {
                            Id = 53,
                            DateAdded = new DateTime(2018, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Mercedes-Benz",
                            Model = "SL-Class",
                            Price = 14066.06m,
                            WarehouseId = 3,
                            Year = 2005
                        },
                        new
                        {
                            Id = 54,
                            DateAdded = new DateTime(2018, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Mitsubishi",
                            Model = "RVR",
                            Price = 22560.18m,
                            WarehouseId = 3,
                            Year = 1995
                        },
                        new
                        {
                            Id = 55,
                            DateAdded = new DateTime(2017, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Volvo",
                            Model = "850",
                            Price = 25762.08m,
                            WarehouseId = 3,
                            Year = 1995
                        },
                        new
                        {
                            Id = 56,
                            DateAdded = new DateTime(2017, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Honda",
                            Model = "del Sol",
                            Price = 18840.96m,
                            WarehouseId = 3,
                            Year = 1994
                        },
                        new
                        {
                            Id = 57,
                            DateAdded = new DateTime(2018, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Infiniti",
                            Model = "Q",
                            Price = 28773.14m,
                            WarehouseId = 3,
                            Year = 1996
                        },
                        new
                        {
                            Id = 58,
                            DateAdded = new DateTime(2018, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Mercedes-Benz",
                            Model = "500E",
                            Price = 17141.08m,
                            WarehouseId = 3,
                            Year = 1992
                        },
                        new
                        {
                            Id = 59,
                            DateAdded = new DateTime(2018, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "GMC",
                            Model = "Envoy XL",
                            Price = 18983.52m,
                            WarehouseId = 3,
                            Year = 2002
                        },
                        new
                        {
                            Id = 60,
                            DateAdded = new DateTime(2018, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Volkswagen",
                            Model = "Touareg 2",
                            Price = 15611.22m,
                            WarehouseId = 3,
                            Year = 2008
                        },
                        new
                        {
                            Id = 61,
                            DateAdded = new DateTime(2017, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Saab",
                            Model = "900",
                            Price = 8771m,
                            WarehouseId = 4,
                            Year = 1987
                        },
                        new
                        {
                            Id = 62,
                            DateAdded = new DateTime(2018, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Mazda",
                            Model = "B-Series",
                            Price = 23407.59m,
                            WarehouseId = 4,
                            Year = 1998
                        },
                        new
                        {
                            Id = 63,
                            DateAdded = new DateTime(2018, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "GMC",
                            Model = "Sierra 3500",
                            Price = 5869.23m,
                            WarehouseId = 4,
                            Year = 2012
                        },
                        new
                        {
                            Id = 64,
                            DateAdded = new DateTime(2018, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Chevrolet",
                            Model = "Corvette",
                            Price = 16630.67m,
                            WarehouseId = 4,
                            Year = 1964
                        },
                        new
                        {
                            Id = 65,
                            DateAdded = new DateTime(2018, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Toyota",
                            Model = "Tacoma",
                            Price = 11597.18m,
                            WarehouseId = 4,
                            Year = 1997
                        },
                        new
                        {
                            Id = 66,
                            DateAdded = new DateTime(2018, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "GMC",
                            Model = "Sonoma",
                            Price = 18248.21m,
                            WarehouseId = 4,
                            Year = 2004
                        },
                        new
                        {
                            Id = 67,
                            DateAdded = new DateTime(2018, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Bugatti",
                            Model = "Veyron",
                            Price = 8051.64m,
                            WarehouseId = 4,
                            Year = 2009
                        },
                        new
                        {
                            Id = 68,
                            DateAdded = new DateTime(2018, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Dodge",
                            Model = "Ram 1500 Club",
                            Price = 14008.3m,
                            WarehouseId = 4,
                            Year = 1996
                        },
                        new
                        {
                            Id = 69,
                            DateAdded = new DateTime(2018, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Land Rover",
                            Model = "Discovery Series II",
                            Price = 18620.19m,
                            WarehouseId = 4,
                            Year = 2001
                        },
                        new
                        {
                            Id = 70,
                            DateAdded = new DateTime(2018, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Volvo",
                            Model = "960",
                            Price = 7316.93m,
                            WarehouseId = 4,
                            Year = 1993
                        },
                        new
                        {
                            Id = 71,
                            DateAdded = new DateTime(2017, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Chrysler",
                            Model = "LHS",
                            Price = 29444.71m,
                            WarehouseId = 4,
                            Year = 2001
                        },
                        new
                        {
                            Id = 72,
                            DateAdded = new DateTime(2017, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Porsche",
                            Model = "944",
                            Price = 7396.95m,
                            WarehouseId = 4,
                            Year = 1984
                        },
                        new
                        {
                            Id = 73,
                            DateAdded = new DateTime(2017, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Subaru",
                            Model = "Legacy",
                            Price = 24491.8m,
                            WarehouseId = 4,
                            Year = 2010
                        },
                        new
                        {
                            Id = 74,
                            DateAdded = new DateTime(2018, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "Volvo",
                            Model = "XC90",
                            Price = 29009.65m,
                            WarehouseId = 4,
                            Year = 2003
                        },
                        new
                        {
                            Id = 75,
                            DateAdded = new DateTime(2018, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Buick",
                            Model = "Skyhawk",
                            Price = 10567.27m,
                            WarehouseId = 4,
                            Year = 1985
                        },
                        new
                        {
                            Id = 76,
                            DateAdded = new DateTime(2018, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = true,
                            Make = "GMC",
                            Model = "Envoy XUV",
                            Price = 20997.71m,
                            WarehouseId = 4,
                            Year = 2004
                        },
                        new
                        {
                            Id = 77,
                            DateAdded = new DateTime(2018, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Volvo",
                            Model = "S60",
                            Price = 28614.95m,
                            WarehouseId = 4,
                            Year = 2009
                        },
                        new
                        {
                            Id = 78,
                            DateAdded = new DateTime(2018, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Pontiac",
                            Model = "Montana",
                            Price = 11221.14m,
                            WarehouseId = 4,
                            Year = 2000
                        },
                        new
                        {
                            Id = 79,
                            DateAdded = new DateTime(2018, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Lexus",
                            Model = "RX",
                            Price = 23194.01m,
                            WarehouseId = 4,
                            Year = 2002
                        },
                        new
                        {
                            Id = 80,
                            DateAdded = new DateTime(2018, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Licensed = false,
                            Make = "Lexus",
                            Model = "RX",
                            Price = 17805.45m,
                            WarehouseId = 4,
                            Year = 2000
                        });
                });

            modelBuilder.Entity("UsedCars.Entities.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 47.13111m,
                            Location = "West wing",
                            Longitude = -61.54801m,
                            Name = "Warehouse A"
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 15.95386m,
                            Location = "East wing",
                            Longitude = 7.06246m,
                            Name = "Warehouse B"
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 39.12788m,
                            Location = "Suid wing",
                            Longitude = -2.71398m,
                            Name = "Warehouse C"
                        },
                        new
                        {
                            Id = 4,
                            Latitude = -70.84354m,
                            Location = "Suid wing",
                            Longitude = 132.22345m,
                            Name = "Warehouse D"
                        });
                });

            modelBuilder.Entity("UsedCars.Entities.Car", b =>
                {
                    b.HasOne("UsedCars.Entities.Warehouse", "Warehouse")
                        .WithMany("Cars")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("UsedCars.Entities.Warehouse", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
